# --- CONFIGURAÇÕES PADRÃO ---
defaultProject: datascience-473223
defaultDataset: dev_work
defaultAssertionDataset: qa_assertions
defaultLocation: US
dataformCoreVersion: 3.0.26

# --- VARIÁVEIS DO PROJETO ---
# A seção de variáveis começa aqui
vars:
    # Fontes de Dados do Teste (Ecommerce)
  dev_work: dev_work
  bronze_ecommerce_bq: "brz_ecommerce"
  silver_ecommerce_bq: "slv_ecommerce"
  gold_ecommerce_bq: "gld_ecommerce"
  
  # LGPD / Governance
  # REPLACE WITH YOUR ACTUAL POLICY TAG ID (e.g., projects/your-project/locations/us/taxonomies/123/policyTags/456)
  pii_policy_tag: "projects/datascience-473223/locations/us/taxonomies/5464689907534065720/policyTags/311878649262498434"

  # Janela para cargas incrementais (útil para o futuro)
  incremental_window_days: "7"
